class Civilian {
    scopeKey = "civilian";
    theme = "civilian";
    side = "civ";
    condition = "playerSide isEqualTo civilian";
    timeMultiplier = 1.0;
    vehicleGarageSide = "civ";

    class Categories {
        class tools {
            title = "Tools";
            description = "Utility items built from refined resources.";
        };
        class sidearms {
            title = "Sidearms";
            description = "Entry-level firearms unlocked through crafting XP.";
        };
        class magazines {
            title = "Magazines";
            description = "Batch-craft ammunition magazines with quantity input.";
        };
        class attachments {
            title = "Attachments";
            description = "Optics and utility attachments.";
        };
        class packs {
            title = "Packs";
            description = "Backpacks and storage support gear.";
        };
        class vehicles {
            title = "Vehicles";
            description = "Civilian vehicles delivered to the crafting player's garage.";
        };
    };

    class Recipes {
        class lockpick {
            title = "Lockpick";
            category = "tools";
            outputType = "virtual";
            outputClass = "lockpick";
            outputAmount = 1;
            requiredLevel = 1;
            craftTime = 18;
            cashCost = 50;
            craftingXP = 35;
            characterXP = 0;
            materials[] = {{"copper_refined",1},{"iron_refined",1}};
            text = "Simple utility tool for civilian mechanical work.";
        };
        class toolkit {
            title = "Toolkit";
            category = "tools";
            outputType = "virtual";
            outputClass = "toolkit";
            outputAmount = 1;
            requiredLevel = 3;
            craftTime = 35;
            cashCost = 250;
            craftingXP = 60;
            characterXP = 0;
            materials[] = {{"iron_refined",4},{"copper_refined",2}};
            text = "Field repair kit assembled from metal components.";
        };
        class rook40 {
            title = "Rook-40";
            category = "sidearms";
            outputType = "gear";
            outputClass = "hgun_Rook40_F";
            outputAmount = 1;
            requiredLevel = 1;
            condition = "license_civ_gun";
            craftTime = 55;
            cashCost = 1200;
            craftingXP = 95;
            characterXP = 0;
            materials[] = {{"iron_refined",5},{"copper_refined",3}};
            text = "Reliable 9mm handgun for licensed civilian owners.";
        };
        class pm9 {
            title = "PM 9mm";
            category = "sidearms";
            outputType = "gear";
            outputClass = "hgun_Pistol_01_F";
            outputAmount = 1;
            requiredLevel = 8;
            condition = "license_civ_gun";
            craftTime = 60;
            cashCost = 1350;
            craftingXP = 115;
            characterXP = 0;
            materials[] = {{"iron_refined",6},{"copper_refined",3},{"glass",1}};
            text = "Compact Apex sidearm with careful machining.";
        };
        class protector {
            title = "Protector SMG";
            category = "sidearms";
            outputType = "gear";
            outputClass = "SMG_05_F";
            outputAmount = 1;
            requiredLevel = 20;
            condition = "license_civ_gun";
            craftTime = 95;
            cashCost = 3500;
            craftingXP = 180;
            characterXP = 0;
            materials[] = {{"iron_refined",12},{"copper_refined",6},{"glass",2}};
            text = "Compact defensive firearm unlocked at the SMG crafting tier.";
        };
        class zubr {
            title = "Zubr .45 Revolver";
            category = "sidearms";
            outputType = "gear";
            outputClass = "hgun_Pistol_heavy_02_F";
            outputAmount = 1;
            requiredLevel = 10;
            condition = "license_civ_gun";
            craftTime = 70;
            cashCost = 1750;
            craftingXP = 135;
            characterXP = 0;
            materials[] = {{"iron_refined",8},{"copper_refined",4}};
            text = "Heavy civilian revolver with a stronger material requirement.";
        };
        class acpc2 {
            title = "ACP-C2";
            category = "sidearms";
            outputType = "gear";
            outputClass = "hgun_ACPC2_F";
            outputAmount = 1;
            requiredLevel = 14;
            condition = "license_civ_gun";
            craftTime = 78;
            cashCost = 2600;
            craftingXP = 150;
            characterXP = 0;
            materials[] = {{"iron_refined",9},{"copper_refined",5},{"glass",1}};
            text = "Licensed .45 pistol crafted from refined metals.";
        };
        class pdw2000 {
            title = "PDW2000";
            category = "sidearms";
            outputType = "gear";
            outputClass = "hgun_PDW2000_F";
            outputAmount = 1;
            requiredLevel = 24;
            condition = "license_civ_gun";
            craftTime = 110;
            cashCost = 4200;
            craftingXP = 210;
            characterXP = 0;
            materials[] = {{"iron_refined",14},{"copper_refined",8},{"glass",2}};
            text = "Higher-tier civilian PDW with more machining time.";
        };
        class mag_16_9 {
            title = "16Rnd 9mm Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "16Rnd_9x21_Mag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 1;
            craftTime = 10;
            cashCost = 15;
            craftingXP = 8;
            characterXP = 0;
            materials[] = {{"copper_refined",1}};
            text = "Standard 9mm magazine. Quantity can be entered before crafting.";
        };
        class mag_6_45 {
            title = "6Rnd .45 Cylinder";
            category = "magazines";
            outputType = "gear";
            outputClass = "6Rnd_45ACP_Cylinder";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 10;
            craftTime = 11;
            cashCost = 20;
            craftingXP = 9;
            characterXP = 0;
            materials[] = {{"copper_refined",1}};
            text = "Zubr cylinder for batch crafting.";
        };
        class mag_9_45 {
            title = "9Rnd .45 Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "9Rnd_45ACP_Mag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 14;
            craftTime = 11;
            cashCost = 22;
            craftingXP = 9;
            characterXP = 0;
            materials[] = {{"copper_refined",1}};
            text = ".45 ACP pistol magazine for batch crafting.";
        };
        class mag_30_9 {
            title = "30Rnd 9mm Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "30Rnd_9x21_Mag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 20;
            craftTime = 12;
            cashCost = 25;
            craftingXP = 10;
            characterXP = 0;
            materials[] = {{"copper_refined",1},{"iron_refined",1}};
            text = "PDW-compatible 9mm magazine.";
        };
        class mag_30_smg {
            title = "30Rnd Protector Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "30Rnd_9x21_Mag_SMG_02";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 20;
            craftTime = 12;
            cashCost = 25;
            craftingXP = 10;
            characterXP = 0;
            materials[] = {{"copper_refined",1},{"iron_refined",1}};
            text = "Protector-compatible magazine for batch crafting.";
        };
        class mag_10_9 {
            title = "10Rnd 9mm Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "10Rnd_9x21_Mag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 8;
            craftTime = 10;
            cashCost = 18;
            craftingXP = 8;
            characterXP = 0;
            materials[] = {{"copper_refined",1}};
            text = "Compact 9mm magazine for licensed pistols.";
        };
        class pistol_flashlight {
            title = "Pistol Flashlight";
            category = "attachments";
            outputType = "gear";
            outputClass = "acc_flashlight_pistol";
            outputAmount = 1;
            requiredLevel = 6;
            craftTime = 28;
            cashCost = 250;
            craftingXP = 45;
            characterXP = 0;
            materials[] = {{"copper_refined",1},{"glass",1}};
            text = "Small utility attachment for sidearms.";
        };
        class smg_aco {
            title = "ACO SMG Optic";
            category = "attachments";
            outputType = "gear";
            outputClass = "optic_ACO_grn_smg";
            outputAmount = 1;
            requiredLevel = 18;
            craftTime = 42;
            cashCost = 750;
            craftingXP = 70;
            characterXP = 0;
            materials[] = {{"glass",2},{"copper_refined",1}};
            text = "Compact optic for SMG platforms.";
        };
        class assault_pack {
            title = "Assault Pack";
            category = "packs";
            outputType = "gear";
            outputClass = "B_AssaultPack_blk";
            outputAmount = 1;
            requiredLevel = 5;
            craftTime = 45;
            cashCost = 900;
            craftingXP = 80;
            characterXP = 0;
            materials[] = {{"iron_refined",2},{"glass",1}};
            text = "Small backpack for light storage.";
        };
        class carryall {
            title = "Carryall Backpack";
            category = "packs";
            outputType = "gear";
            outputClass = "B_Carryall_oli";
            outputAmount = 1;
            requiredLevel = 55;
            craftTime = 90;
            cashCost = 2500;
            craftingXP = 170;
            characterXP = 0;
            materials[] = {{"iron_refined",6},{"copper_refined",4},{"glass",2}};
            text = "Large pack unlocked at the large backpack crafting tier.";
        };
        class quadbike {
            title = "Quadbike";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "B_Quadbike_01_F";
            outputAmount = 1;
            requiredLevel = 18;
            condition = "license_civ_driver";
            craftTime = 150;
            cashCost = 3500;
            craftingXP = 240;
            characterXP = 0;
            materials[] = {{"iron_refined",18},{"copper_refined",8},{"oil_processed",4}};
            text = "Delivered inactive to your civilian garage.";
        };
        class offroad {
            title = "Offroad";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "C_Offroad_01_F";
            outputAmount = 1;
            requiredLevel = 80;
            condition = "license_civ_driver";
            craftTime = 260;
            cashCost = 12500;
            craftingXP = 420;
            characterXP = 0;
            materials[] = {{"iron_refined",45},{"copper_refined",18},{"glass",10},{"oil_processed",8}};
            text = "Full vehicle build sent to your garage when complete.";
        };
        class hatchback {
            title = "Hatchback";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "C_Hatchback_01_F";
            outputAmount = 1;
            requiredLevel = 42;
            condition = "license_civ_driver";
            craftTime = 220;
            cashCost = 9000;
            craftingXP = 340;
            characterXP = 0;
            materials[] = {{"iron_refined",34},{"copper_refined",14},{"glass",8},{"oil_processed",6}};
            text = "Compact civilian vehicle delivered inactive to your garage.";
        };
        class suv {
            title = "SUV";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "C_SUV_01_F";
            outputAmount = 1;
            requiredLevel = 88;
            condition = "license_civ_driver";
            craftTime = 310;
            cashCost = 22000;
            craftingXP = 520;
            characterXP = 0;
            materials[] = {{"iron_refined",62},{"copper_refined",24},{"glass",14},{"oil_processed",12},{"diamond_cut",1}};
            text = "Higher-end civilian vehicle crafted from premium parts.";
        };
        class transport_van {
            title = "Transport Van";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "C_Van_01_transport_F";
            outputAmount = 1;
            requiredLevel = 92;
            condition = "license_civ_driver";
            craftTime = 345;
            cashCost = 30000;
            craftingXP = 600;
            characterXP = 0;
            materials[] = {{"iron_refined",78},{"copper_refined",32},{"glass",16},{"oil_processed",16},{"diamond_cut",2}};
            text = "Large civilian transport build sent to your garage.";
        };
    };
};
