class LawEnforcement {
    scopeKey = "leo";
    theme = "leo";
    side = "cop";
    condition = "playerSide isEqualTo west";
    timeMultiplier = 1.35;
    vehicleGarageSide = "cop";
    department = "kcso";

    class Categories {
        class duty {
            title = "Duty Gear";
            description = "Baseline issued tools and equipment.";
        };
        class less_lethal {
            title = "Less Lethal";
            description = "Taser platforms and training devices.";
        };
        class sidearms {
            title = "Sidearms";
            description = "Rank-gated duty pistols.";
        };
        class long_guns {
            title = "Long Guns";
            description = "Supervisor and specialty weapons.";
        };
        class attachments {
            title = "Attachments";
            description = "Optics, lights, and muzzle devices.";
        };
        class magazines {
            title = "Magazines";
            description = "Batch craft approved duty magazines.";
        };
        class vehicles {
            title = "Vehicles";
            description = "Department vehicles delivered to the officer's police garage.";
        };
    };

    class Recipes {
        class binocular {
            title = "Field Binoculars";
            category = "duty";
            outputType = "gear";
            outputClass = "Binocular";
            outputAmount = 1;
            requiredLevel = 1;
            craftTime = 35;
            cashCost = 50;
            craftingXP = 45;
            characterXP = 0;
            materials[] = {{"glass",2},{"copper_refined",1}};
            text = "Standard observation equipment for sworn personnel.";
        };
        class gps {
            title = "Duty GPS";
            category = "duty";
            outputType = "gear";
            outputClass = "ItemGPS";
            outputAmount = 1;
            requiredLevel = 1;
            craftTime = 35;
            cashCost = 50;
            craftingXP = 45;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"glass",1}};
            text = "Navigation unit assembled for department use.";
        };
        class first_aid {
            title = "First Aid Kit";
            category = "duty";
            outputType = "gear";
            outputClass = "FirstAidKit";
            outputAmount = 1;
            requiredLevel = 1;
            craftTime = 30;
            cashCost = 40;
            craftingXP = 35;
            characterXP = 0;
            materials[] = {{"glass",1},{"copper_refined",1}};
            text = "Basic medical kit for duty carry.";
        };
        class nvg {
            title = "Duty NVGs";
            category = "duty";
            outputType = "gear";
            outputClass = "NVGoggles";
            outputAmount = 1;
            requiredLevel = 8;
            craftTime = 75;
            cashCost = 1200;
            craftingXP = 110;
            characterXP = 0;
            materials[] = {{"glass",5},{"copper_refined",3},{"iron_refined",2}};
            text = "Night-vision equipment for qualified duty use.";
        };
        class flashbang {
            title = "Flashbang";
            category = "less_lethal";
            outputType = "gear";
            outputClass = "HandGrenade_Stone";
            outputAmount = 1;
            requiredLevel = 8;
            craftTime = 85;
            cashCost = 650;
            craftingXP = 125;
            characterXP = 0;
            materials[] = {{"iron_refined",4},{"copper_refined",2},{"oil_processed",1}};
            text = "Less-lethal distraction device. LEO crafting takes longer for accountability.";
        };
        class stun_pistol {
            title = "Stun Pistol";
            category = "less_lethal";
            outputType = "gear";
            outputClass = "hgun_P07_snds_F";
            outputAmount = 1;
            requiredLevel = 1;
            craftTime = 90;
            cashCost = 900;
            craftingXP = 130;
            characterXP = 0;
            materials[] = {{"iron_refined",6},{"copper_refined",4},{"glass",1}};
            text = "Less-lethal sidearm for patrol work.";
        };
        class taser_rifle {
            title = "Taser Rifle";
            category = "less_lethal";
            outputType = "gear";
            outputClass = "arifle_SDAR_F";
            outputAmount = 1;
            requiredLevel = 18;
            craftTime = 150;
            cashCost = 3500;
            craftingXP = 220;
            characterXP = 0;
            materials[] = {{"iron_refined",18},{"copper_refined",10},{"glass",3}};
            text = "Long less-lethal platform for trained officers.";
        };
        class g17 {
            title = "G17 Duty Sidearm";
            category = "sidearms";
            outputType = "gear";
            outputClass = "RH_g17";
            outputAmount = 1;
            requiredLevel = 5;
            craftTime = 115;
            cashCost = 2500;
            craftingXP = 170;
            characterXP = 0;
            materials[] = {{"iron_refined",9},{"copper_refined",5},{"glass",1}};
            text = "Standard duty sidearm.";
        };
        class p07 {
            title = "P07 Duty Sidearm";
            category = "sidearms";
            outputType = "gear";
            outputClass = "hgun_P07_F";
            outputAmount = 1;
            requiredLevel = 6;
            craftTime = 105;
            cashCost = 2200;
            craftingXP = 155;
            characterXP = 0;
            materials[] = {{"iron_refined",9},{"copper_refined",5},{"glass",1}};
            text = "Standard P07 duty pistol.";
        };
        class p07_khk {
            title = "P07 Khaki";
            category = "sidearms";
            outputType = "gear";
            outputClass = "hgun_P07_khk_F";
            outputAmount = 1;
            requiredLevel = 6;
            craftTime = 105;
            cashCost = 2200;
            craftingXP = 155;
            characterXP = 0;
            materials[] = {{"iron_refined",9},{"copper_refined",5},{"glass",1}};
            text = "Alternate P07 duty pistol finish.";
        };
        class kimber {
            title = "Kimber Duty Pistol";
            category = "sidearms";
            outputType = "gear";
            outputClass = "RH_kimber_nw";
            outputAmount = 1;
            requiredLevel = 12;
            rank = "deputy";
            craftTime = 130;
            cashCost = 3000;
            craftingXP = 190;
            characterXP = 0;
            materials[] = {{"iron_refined",11},{"copper_refined",6},{"glass",1}};
            text = "Deputy-and-above duty pistol.";
        };
        class heavy_45 {
            title = "4-Five Duty Pistol";
            category = "sidearms";
            outputType = "gear";
            outputClass = "hgun_Pistol_heavy_01_F";
            outputAmount = 1;
            requiredLevel = 16;
            rank = "deputy";
            craftTime = 145;
            cashCost = 3400;
            craftingXP = 210;
            characterXP = 0;
            materials[] = {{"iron_refined",13},{"copper_refined",7},{"glass",2}};
            text = "Deputy-and-above .45 duty pistol.";
        };
        class acpc2 {
            title = "ACP-C2 Duty Pistol";
            category = "sidearms";
            outputType = "gear";
            outputClass = "hgun_ACPC2_F";
            outputAmount = 1;
            requiredLevel = 35;
            rank = "sergeant";
            craftTime = 190;
            cashCost = 6500;
            craftingXP = 320;
            characterXP = 0;
            materials[] = {{"iron_refined",22},{"copper_refined",12},{"glass",3},{"diamond_cut",1}};
            text = "Sergeant-and-above heavy sidearm.";
        };
        class sting {
            title = "Sting SMG";
            category = "long_guns";
            outputType = "gear";
            outputClass = "SMG_02_ACO_F";
            outputAmount = 1;
            requiredLevel = 32;
            rank = "corporal";
            craftTime = 220;
            cashCost = 8500;
            craftingXP = 380;
            characterXP = 0;
            materials[] = {{"iron_refined",30},{"copper_refined",16},{"glass",4},{"diamond_cut",1}};
            text = "Corporal-and-above compact duty weapon.";
        };
        class ru556 {
            title = "RU556 Patrol Rifle";
            category = "long_guns";
            outputType = "gear";
            outputClass = "hlc_rifle_RU5562";
            outputAmount = 1;
            requiredLevel = 40;
            rank = "corporal";
            craftTime = 240;
            cashCost = 9000;
            craftingXP = 420;
            characterXP = 0;
            materials[] = {{"iron_refined",34},{"copper_refined",18},{"glass",5},{"diamond_cut",1}};
            text = "Corporal-and-above patrol rifle.";
        };
        class mx {
            title = "MX Patrol Rifle";
            category = "long_guns";
            outputType = "gear";
            outputClass = "arifle_MX_F";
            outputAmount = 1;
            requiredLevel = 44;
            rank = "corporal";
            craftTime = 255;
            cashCost = 10000;
            craftingXP = 450;
            characterXP = 0;
            materials[] = {{"iron_refined",38},{"copper_refined",20},{"glass",6},{"diamond_cut",1}};
            text = "Corporal-and-above patrol rifle.";
        };
        class mxc {
            title = "MXC Patrol Rifle";
            category = "long_guns";
            outputType = "gear";
            outputClass = "arifle_MXC_F";
            outputAmount = 1;
            requiredLevel = 50;
            rank = "sergeant";
            craftTime = 285;
            cashCost = 12000;
            craftingXP = 510;
            characterXP = 0;
            materials[] = {{"iron_refined",44},{"copper_refined",23},{"glass",7},{"diamond_cut",2}};
            text = "Sergeant-and-above compact MX platform.";
        };
        class cmr {
            title = "CMR-76";
            category = "long_guns";
            outputType = "gear";
            outputClass = "srifle_DMR_07_blk_F";
            outputAmount = 1;
            requiredLevel = 55;
            rank = "sergeant";
            subdivisions[] = {"swat"};
            craftTime = 300;
            cashCost = 13500;
            craftingXP = 560;
            characterXP = 0;
            materials[] = {{"iron_refined",48},{"copper_refined",24},{"glass",9},{"diamond_cut",2}};
            text = "Sergeant-and-above precision platform.";
        };
        class pistol_light {
            title = "Pistol Light";
            category = "attachments";
            outputType = "gear";
            outputClass = "RH_X300";
            outputAmount = 1;
            requiredLevel = 6;
            craftTime = 45;
            cashCost = 250;
            craftingXP = 60;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"glass",1}};
            text = "Pistol light attachment.";
        };
        class pistol_flashlight {
            title = "Pistol Flashlight";
            category = "attachments";
            outputType = "gear";
            outputClass = "acc_flashlight_pistol";
            outputAmount = 1;
            requiredLevel = 6;
            rank = "deputy";
            craftTime = 45;
            cashCost = 250;
            craftingXP = 60;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"glass",1}};
            text = "Deputy-and-above pistol flashlight attachment.";
        };
        class pistol_suppressor {
            title = "9mm Suppressor";
            category = "attachments";
            outputType = "gear";
            outputClass = "muzzle_snds_L";
            outputAmount = 1;
            requiredLevel = 14;
            craftTime = 60;
            cashCost = 700;
            craftingXP = 90;
            characterXP = 0;
            materials[] = {{"iron_refined",4},{"copper_refined",3}};
            text = "Department-approved 9mm suppressor.";
        };
        class optic_mrd {
            title = "MRD Optic";
            category = "attachments";
            outputType = "gear";
            outputClass = "optic_MRD";
            outputAmount = 1;
            requiredLevel = 10;
            rank = "deputy";
            craftTime = 65;
            cashCost = 900;
            craftingXP = 95;
            characterXP = 0;
            materials[] = {{"glass",3},{"copper_refined",2}};
            text = "Deputy-and-above mini reflex sight.";
        };
        class rifle_flashlight {
            title = "Rifle Flashlight";
            category = "attachments";
            outputType = "gear";
            outputClass = "acc_flashlight";
            outputAmount = 1;
            requiredLevel = 28;
            rank = "corporal";
            craftTime = 55;
            cashCost = 550;
            craftingXP = 75;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"glass",1}};
            text = "Corporal-and-above rifle flashlight attachment.";
        };
        class optic_holo {
            title = "Holosight";
            category = "attachments";
            outputType = "gear";
            outputClass = "optic_Holosight";
            outputAmount = 1;
            requiredLevel = 32;
            rank = "corporal";
            craftTime = 70;
            cashCost = 1000;
            craftingXP = 110;
            characterXP = 0;
            materials[] = {{"glass",4},{"copper_refined",3}};
            text = "Corporal-and-above patrol rifle sight.";
        };
        class optic_arco {
            title = "ARCO Optic";
            category = "attachments";
            outputType = "gear";
            outputClass = "optic_Arco";
            outputAmount = 1;
            requiredLevel = 40;
            rank = "corporal";
            craftTime = 95;
            cashCost = 1500;
            craftingXP = 145;
            characterXP = 0;
            materials[] = {{"glass",5},{"copper_refined",4},{"iron_refined",2}};
            text = "Corporal-and-above rifle optic.";
        };
        class rifle_suppressor {
            title = "6.5mm Suppressor";
            category = "attachments";
            outputType = "gear";
            outputClass = "muzzle_snds_H";
            outputAmount = 1;
            requiredLevel = 44;
            rank = "corporal";
            craftTime = 95;
            cashCost = 2100;
            craftingXP = 160;
            characterXP = 0;
            materials[] = {{"iron_refined",8},{"copper_refined",5},{"diamond_cut",1}};
            text = "Corporal-and-above rifle suppressor.";
        };
        class mag_16_9 {
            title = "16Rnd 9mm Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "16Rnd_9x21_Mag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 1;
            craftTime = 16;
            cashCost = 15;
            craftingXP = 10;
            characterXP = 0;
            materials[] = {{"copper_refined",1}};
            text = "Standard duty 9mm magazine.";
        };
        class mag_g17 {
            title = "G17 Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "RH_17Rnd_9x19_g17";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 5;
            craftTime = 18;
            cashCost = 20;
            craftingXP = 12;
            characterXP = 0;
            materials[] = {{"copper_refined",1},{"iron_refined",1}};
            text = "Standard duty magazine with batch quantity support.";
        };
        class mag_11_45 {
            title = "11Rnd .45 Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "11Rnd_45ACP_Mag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 16;
            rank = "deputy";
            craftTime = 18;
            cashCost = 25;
            craftingXP = 14;
            characterXP = 0;
            materials[] = {{"copper_refined",1},{"iron_refined",1}};
            text = "Deputy-and-above .45 duty magazine.";
        };
        class mag_taser {
            title = "Taser Rifle Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "20Rnd_556x45_UW_mag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 18;
            craftTime = 18;
            cashCost = 20;
            craftingXP = 12;
            characterXP = 0;
            materials[] = {{"copper_refined",1},{"iron_refined",1}};
            text = "Less-lethal rifle magazine.";
        };
        class mag_30_65 {
            title = "30Rnd 6.5mm Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "30Rnd_65x39_caseless_mag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 40;
            rank = "corporal";
            craftTime = 22;
            cashCost = 35;
            craftingXP = 16;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"iron_refined",1}};
            text = "Corporal-and-above MX magazine.";
        };
        class mag_30_9 {
            title = "30Rnd 9mm Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "30Rnd_9x21_Mag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 32;
            rank = "corporal";
            craftTime = 20;
            cashCost = 30;
            craftingXP = 14;
            characterXP = 0;
            materials[] = {{"copper_refined",1},{"iron_refined",1}};
            text = "Corporal-and-above SMG magazine.";
        };
        class mag_9_45 {
            title = "9Rnd .45 Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "9Rnd_45ACP_Mag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 35;
            rank = "sergeant";
            craftTime = 20;
            cashCost = 30;
            craftingXP = 14;
            characterXP = 0;
            materials[] = {{"copper_refined",1},{"iron_refined",1}};
            text = "Sergeant-and-above .45 duty magazine.";
        };
        class mag_650 {
            title = "20Rnd 6.5mm Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "20Rnd_650x39_Cased_Mag_F";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 50;
            rank = "sergeant";
            craftTime = 24;
            cashCost = 45;
            craftingXP = 18;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"iron_refined",2}};
            text = "Sergeant-and-above CMR magazine.";
        };
        class mag_556 {
            title = "5.56 EPR Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "hlc_30rnd_556x45_EPR";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 40;
            rank = "corporal";
            craftTime = 22;
            cashCost = 35;
            craftingXP = 16;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"iron_refined",1}};
            text = "Patrol rifle magazine.";
        };
        class patrol_offroad {
            title = "Patrol Offroad";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "C_Offroad_01_F";
            outputAmount = 1;
            requiredLevel = 35;
            craftTime = 300;
            cashCost = 12000;
            craftingXP = 480;
            characterXP = 0;
            materials[] = {{"iron_refined",60},{"copper_refined",28},{"glass",14},{"oil_processed",12}};
            text = "Basic patrol vehicle delivered to the officer's police garage.";
        };
        class patrol_suv {
            title = "Patrol SUV";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "C_SUV_01_F";
            outputAmount = 1;
            requiredLevel = 55;
            craftTime = 360;
            cashCost = 18000;
            craftingXP = 610;
            characterXP = 0;
            materials[] = {{"iron_refined",86},{"copper_refined",40},{"glass",18},{"oil_processed",18},{"diamond_cut",2}};
            text = "Patrol SUV delivered inactive to the police garage.";
        };
        class sport_hatchback {
            title = "Sport Hatchback Patrol";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "C_Hatchback_01_sport_F";
            outputAmount = 1;
            requiredLevel = 70;
            rank = "deputy";
            craftTime = 430;
            cashCost = 30000;
            craftingXP = 780;
            characterXP = 0;
            materials[] = {{"iron_refined",112},{"copper_refined",52},{"glass",24},{"oil_processed",26},{"diamond_cut",4}};
            text = "Deputy-and-above pursuit vehicle.";
        };
        class hunter {
            title = "Hunter MRAP";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "B_MRAP_01_F";
            outputAmount = 1;
            requiredLevel = 88;
            rank = "corporal";
            craftTime = 620;
            cashCost = 65000;
            craftingXP = 1150;
            characterXP = 0;
            materials[] = {{"iron_refined",210},{"copper_refined",90},{"glass",32},{"oil_processed",46},{"diamond_cut",8}};
            text = "Corporal-and-above armored patrol vehicle.";
        };
        class hunter_hmg {
            title = "Hunter HMG";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "B_MRAP_01_hmg_F";
            outputAmount = 1;
            requiredLevel = 100;
            rank = "sergeant";
            subdivisions[] = {"swat"};
            rolePermissions[] = {"leo.tactical.swat"};
            craftTime = 780;
            cashCost = 125000;
            craftingXP = 1600;
            characterXP = 0;
            materials[] = {{"iron_refined",310},{"copper_refined",135},{"glass",46},{"oil_processed",70},{"diamond_cut",14}};
            text = "Sergeant SWAT armored vehicle with the longest police ground craft.";
        };
        class patrol_cvpi {
            title = "2011 CVPI Patrol";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "AG_CROWNVIC_Police_AG";
            outputAmount = 1;
            requiredLevel = 80;
            rank = "deputy";
            subdivisions[] = {};
            craftTime = 420;
            cashCost = 25000;
            craftingXP = 760;
            characterXP = 0;
            materials[] = {{"iron_refined",110},{"copper_refined",55},{"glass",22},{"oil_processed",24},{"diamond_cut",4}};
            text = "Patrol vehicle delivered to the officer's police garage.";
        };
        class hsu_mustang {
            title = "HSU Mustang GT";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "AG_MustangGT15_HSU_AG";
            outputAmount = 1;
            requiredLevel = 90;
            rank = "deputy";
            subdivisions[] = {"hsu"};
            rolePermissions[] = {"leo.vehicle.hsu"};
            craftTime = 520;
            cashCost = 42000;
            craftingXP = 930;
            characterXP = 0;
            materials[] = {{"iron_refined",140},{"copper_refined",72},{"glass",30},{"oil_processed",34},{"diamond_cut",6}};
            text = "HSU vehicle delivered inactive to the police garage.";
        };
        class bearcat {
            title = "SWAT Bearcat";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "AG_Bearcat_KCSO_AG";
            outputAmount = 1;
            requiredLevel = 100;
            rank = "sergeant";
            subdivisions[] = {"swat"};
            rolePermissions[] = {"leo.tactical.swat"};
            craftTime = 700;
            cashCost = 85000;
            craftingXP = 1250;
            characterXP = 0;
            materials[] = {{"iron_refined",230},{"copper_refined",110},{"glass",38},{"oil_processed",50},{"diamond_cut",10}};
            text = "Heavy tactical vehicle. This is one of the longest LEO crafts.";
        };
        class patrol_hummingbird {
            title = "KCSO Patrol Hummingbird";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "AG_Hummingbird_Police";
            outputAmount = 1;
            requiredLevel = 100;
            rank = "sergeant";
            subdivisions[] = {};
            condition = "license_cop_cAir";
            craftTime = 760;
            cashCost = 110000;
            craftingXP = 1400;
            characterXP = 0;
            materials[] = {{"iron_refined",250},{"copper_refined",130},{"glass",50},{"oil_processed",60},{"diamond_cut",12}};
            text = "Certified aviation craft delivered to the police air garage.";
        };
        class police_hummingbird {
            title = "Police Hummingbird";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "B_Heli_Light_01_F";
            outputAmount = 1;
            requiredLevel = 100;
            rank = "sergeant";
            condition = "license_cop_cAir";
            craftTime = 740;
            cashCost = 100000;
            craftingXP = 1350;
            characterXP = 0;
            materials[] = {{"iron_refined",240},{"copper_refined",120},{"glass",48},{"oil_processed",58},{"diamond_cut",12}};
            text = "Police light helicopter delivered inactive to the air garage.";
        };
        class ghosthawk {
            title = "Ghosthawk Transport";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "B_Heli_Transport_01_F";
            outputAmount = 1;
            requiredLevel = 100;
            rank = "lieutenant";
            condition = "license_cop_cAir";
            craftTime = 900;
            cashCost = 180000;
            craftingXP = 1900;
            characterXP = 0;
            materials[] = {{"iron_refined",360},{"copper_refined",170},{"glass",70},{"oil_processed",95},{"diamond_cut",22}};
            text = "Lieutenant aviation transport craft with a very long build time.";
        };
        class patrol_boat {
            title = "Patrol Boat";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "B_Boat_Transport_01_F";
            outputAmount = 1;
            requiredLevel = 45;
            condition = "license_cop_cg";
            craftTime = 280;
            cashCost = 9000;
            craftingXP = 430;
            characterXP = 0;
            materials[] = {{"iron_refined",54},{"copper_refined",26},{"glass",8},{"oil_processed",14}};
            text = "Coast guard patrol boat delivered to the police garage.";
        };
        class police_motorboat {
            title = "Police Motorboat";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "C_Boat_Civil_01_police_F";
            outputAmount = 1;
            requiredLevel = 58;
            condition = "license_cop_cg";
            craftTime = 340;
            cashCost = 18000;
            craftingXP = 570;
            characterXP = 0;
            materials[] = {{"iron_refined",74},{"copper_refined",36},{"glass",14},{"oil_processed",20},{"diamond_cut",2}};
            text = "Police motorboat for certified marine officers.";
        };
        class armed_boat {
            title = "Armed Patrol Boat";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "B_Boat_Armed_01_minigun_F";
            outputAmount = 1;
            requiredLevel = 95;
            rank = "sergeant";
            condition = "license_cop_cg";
            craftTime = 760;
            cashCost = 90000;
            craftingXP = 1450;
            characterXP = 0;
            materials[] = {{"iron_refined",260},{"copper_refined",125},{"glass",35},{"oil_processed",62},{"diamond_cut",12}};
            text = "Sergeant-and-above marine response craft.";
        };
    };
};
