class Rebel {
    scopeKey = "rebel";
    theme = "rebel";
    side = "civ";
    condition = "playerSide isEqualTo civilian && {license_civ_rebel}";
    timeMultiplier = 0.9;
    vehicleGarageSide = "civ";

    class Categories {
        class tools {
            title = "Restricted Tools";
            description = "Black-market utility items and breach tools.";
        };
        class sidearms {
            title = "Sidearms";
            description = "Concealable firearms and rebel handguns.";
        };
        class rifles {
            title = "Rifles";
            description = "Higher-tier rebel firearms with stronger material costs.";
        };
        class magazines {
            title = "Magazines";
            description = "Batch craft rebel ammunition magazines.";
        };
        class attachments {
            title = "Attachments";
            description = "Rebel optics and weapon accessories.";
        };
        class vehicles {
            title = "Vehicles";
            description = "Rebel vehicles delivered to the player's civilian garage.";
        };
    };

    class Recipes {
        class boltcutters {
            title = "Bolt Cutters";
            category = "tools";
            outputType = "virtual";
            outputClass = "boltcutter";
            outputAmount = 1;
            requiredLevel = 12;
            craftTime = 45;
            cashCost = 1500;
            craftingXP = 115;
            characterXP = 0;
            materials[] = {{"iron_refined",8},{"copper_refined",2}};
            text = "Illegal breach tool for rebel operations.";
        };
        class blasting_charge {
            title = "Blasting Charge";
            category = "tools";
            outputType = "virtual";
            outputClass = "blastingcharge";
            outputAmount = 1;
            requiredLevel = 42;
            craftTime = 115;
            cashCost = 9500;
            craftingXP = 260;
            characterXP = 0;
            materials[] = {{"iron_refined",12},{"copper_refined",8},{"oil_processed",6},{"diamond_cut",1}};
            text = "High-risk explosive device with a long craft time.";
        };
        class acpc2 {
            title = "ACP-C2";
            category = "sidearms";
            outputType = "gear";
            outputClass = "hgun_ACPC2_F";
            outputAmount = 1;
            requiredLevel = 14;
            craftTime = 70;
            cashCost = 2400;
            craftingXP = 130;
            characterXP = 0;
            materials[] = {{"iron_refined",7},{"copper_refined",4},{"glass",1}};
            text = "Heavy sidearm for rebel workbench owners.";
        };
        class pdw2000 {
            title = "PDW2000";
            category = "sidearms";
            outputType = "gear";
            outputClass = "hgun_PDW2000_F";
            outputAmount = 1;
            requiredLevel = 20;
            craftTime = 95;
            cashCost = 4200;
            craftingXP = 185;
            characterXP = 0;
            materials[] = {{"iron_refined",12},{"copper_refined",6},{"glass",2}};
            text = "Compact rebel PDW unlocked with SMG crafting.";
        };
        class trg20 {
            title = "TRG-20";
            category = "rifles";
            outputType = "gear";
            outputClass = "arifle_TRG20_F";
            outputAmount = 1;
            requiredLevel = 32;
            craftTime = 130;
            cashCost = 9500;
            craftingXP = 260;
            characterXP = 0;
            materials[] = {{"iron_refined",22},{"copper_refined",12},{"glass",3}};
            text = "Entry rebel rifle with moderate material cost.";
        };
        class katiba {
            title = "Katiba Rifle";
            category = "rifles";
            outputType = "gear";
            outputClass = "arifle_Katiba_F";
            outputAmount = 1;
            requiredLevel = 40;
            craftTime = 150;
            cashCost = 12500;
            craftingXP = 320;
            characterXP = 0;
            materials[] = {{"iron_refined",26},{"copper_refined",14},{"glass",4},{"diamond_cut",1}};
            text = "Restricted rifle unlocked at assault rifle crafting tier.";
        };
        class sdar {
            title = "SDAR Rifle";
            category = "rifles";
            outputType = "gear";
            outputClass = "arifle_SDAR_F";
            outputAmount = 1;
            requiredLevel = 38;
            craftTime = 142;
            cashCost = 11000;
            craftingXP = 295;
            characterXP = 0;
            materials[] = {{"iron_refined",24},{"copper_refined",14},{"glass",4}};
            text = "Utility rifle platform for rebel operations.";
        };
        class mk20 {
            title = "Mk20 Rifle";
            category = "rifles";
            outputType = "gear";
            outputClass = "arifle_Mk20_F";
            outputAmount = 1;
            requiredLevel = 46;
            craftTime = 165;
            cashCost = 14500;
            craftingXP = 350;
            characterXP = 0;
            materials[] = {{"iron_refined",30},{"copper_refined",16},{"glass",5},{"diamond_cut",1}};
            text = "Advanced rebel long gun with a heavier build cost.";
        };
        class ak12 {
            title = "AK-12";
            category = "rifles";
            outputType = "gear";
            outputClass = "arifle_AK12_F";
            outputAmount = 1;
            requiredLevel = 52;
            craftTime = 185;
            cashCost = 16000;
            craftingXP = 390;
            characterXP = 0;
            materials[] = {{"iron_refined",36},{"copper_refined",18},{"glass",5},{"diamond_cut",1}};
            text = "Heavy rebel rifle with a long receiver build.";
        };
        class aks {
            title = "AKS-74U";
            category = "rifles";
            outputType = "gear";
            outputClass = "arifle_AKS_F";
            outputAmount = 1;
            requiredLevel = 48;
            craftTime = 165;
            cashCost = 13500;
            craftingXP = 350;
            characterXP = 0;
            materials[] = {{"iron_refined",30},{"copper_refined",16},{"glass",4},{"diamond_cut",1}};
            text = "Compact AK platform for mobile rebels.";
        };
        class akm {
            title = "AKM";
            category = "rifles";
            outputType = "gear";
            outputClass = "arifle_AKM_F";
            outputAmount = 1;
            requiredLevel = 50;
            craftTime = 175;
            cashCost = 14500;
            craftingXP = 370;
            characterXP = 0;
            materials[] = {{"iron_refined",34},{"copper_refined",17},{"glass",4},{"diamond_cut",1}};
            text = "Durable rebel rifle with heavy metal demand.";
        };
        class arx {
            title = "Type 115";
            category = "rifles";
            outputType = "gear";
            outputClass = "arifle_ARX_blk_F";
            outputAmount = 1;
            requiredLevel = 70;
            craftTime = 240;
            cashCost = 26000;
            craftingXP = 560;
            characterXP = 0;
            materials[] = {{"iron_refined",58},{"copper_refined",28},{"glass",8},{"diamond_cut",3}};
            text = "Experimental rebel rifle requiring premium parts.";
        };
        class spar {
            title = "SPAR-16";
            category = "rifles";
            outputType = "gear";
            outputClass = "arifle_SPAR_01_blk_F";
            outputAmount = 1;
            requiredLevel = 62;
            craftTime = 215;
            cashCost = 21000;
            craftingXP = 500;
            characterXP = 0;
            materials[] = {{"iron_refined",48},{"copper_refined",24},{"glass",7},{"diamond_cut",2}};
            text = "High-end 5.56 rifle for advanced rebel crafting.";
        };
        class ctar {
            title = "CAR-95";
            category = "rifles";
            outputType = "gear";
            outputClass = "arifle_CTAR_blk_F";
            outputAmount = 1;
            requiredLevel = 64;
            craftTime = 220;
            cashCost = 22000;
            craftingXP = 520;
            characterXP = 0;
            materials[] = {{"iron_refined",50},{"copper_refined",25},{"glass",7},{"diamond_cut",2}};
            text = "Compact bullpup rifle for advanced rebel work.";
        };
        class rahim {
            title = "Rahim 7.62";
            category = "rifles";
            outputType = "gear";
            outputClass = "srifle_DMR_01_F";
            outputAmount = 1;
            requiredLevel = 78;
            craftTime = 285;
            cashCost = 32000;
            craftingXP = 690;
            characterXP = 0;
            materials[] = {{"iron_refined",76},{"copper_refined",34},{"glass",12},{"diamond_cut",4}};
            text = "Long-range rebel rifle with a major resource requirement.";
        };
        class mag_30_65 {
            title = "30Rnd 6.5mm Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "30Rnd_65x39_caseless_green";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 40;
            craftTime = 16;
            cashCost = 45;
            craftingXP = 14;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"iron_refined",1}};
            text = "Katiba-compatible magazine with batch quantity support.";
        };
        class mag_30_556 {
            title = "30Rnd 5.56mm Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "30Rnd_556x45_Stanag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 46;
            craftTime = 16;
            cashCost = 45;
            craftingXP = 14;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"iron_refined",1}};
            text = "Mk20-compatible magazine with batch quantity support.";
        };
        class mag_762_39 {
            title = "30Rnd 7.62x39 Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "30Rnd_762x39_Mag_F";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 50;
            craftTime = 18;
            cashCost = 55;
            craftingXP = 18;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"iron_refined",2}};
            text = "AK-family magazine for batch crafting.";
        };
        class mag_545_39 {
            title = "30Rnd 5.45x39 Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "30Rnd_545x39_Mag_F";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 48;
            craftTime = 17;
            cashCost = 50;
            craftingXP = 16;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"iron_refined",1}};
            text = "AKS magazine with quantity support.";
        };
        class mag_762_54 {
            title = "10Rnd 7.62x54 Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "10Rnd_762x54_Mag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 80;
            requiredLevel = 78;
            craftTime = 22;
            cashCost = 90;
            craftingXP = 28;
            characterXP = 0;
            materials[] = {{"copper_refined",3},{"iron_refined",2}};
            text = "Rahim magazine for precision rifle crafting.";
        };
        class mag_sdar {
            title = "20Rnd SDAR Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "20Rnd_556x45_UW_mag";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 38;
            craftTime = 16;
            cashCost = 40;
            craftingXP = 14;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"iron_refined",1}};
            text = "SDAR-compatible magazine with batch quantity support.";
        };
        class mag_580 {
            title = "30Rnd 5.8mm Magazine";
            category = "magazines";
            outputType = "gear";
            outputClass = "30Rnd_580x42_Mag_F";
            outputAmount = 1;
            allowQuantity = 1;
            maxQuantity = 100;
            requiredLevel = 64;
            craftTime = 19;
            cashCost = 65;
            craftingXP = 20;
            characterXP = 0;
            materials[] = {{"copper_refined",2},{"iron_refined",2}};
            text = "CAR-95 magazine with batch quantity support.";
        };
        class optic_aco {
            title = "ACO Optic";
            category = "attachments";
            outputType = "gear";
            outputClass = "optic_ACO_grn";
            outputAmount = 1;
            requiredLevel = 34;
            craftTime = 48;
            cashCost = 1200;
            craftingXP = 80;
            characterXP = 0;
            materials[] = {{"glass",3},{"copper_refined",2}};
            text = "Basic rebel optic.";
        };
        class optic_holo {
            title = "Holosight";
            category = "attachments";
            outputType = "gear";
            outputClass = "optic_Holosight";
            outputAmount = 1;
            requiredLevel = 38;
            craftTime = 52;
            cashCost = 1400;
            craftingXP = 90;
            characterXP = 0;
            materials[] = {{"glass",3},{"copper_refined",2}};
            text = "Close-range optic for rebel rifles.";
        };
        class optic_hamr {
            title = "RCO / HAMR";
            category = "attachments";
            outputType = "gear";
            outputClass = "optic_Hamr";
            outputAmount = 1;
            requiredLevel = 60;
            craftTime = 75;
            cashCost = 2600;
            craftingXP = 135;
            characterXP = 0;
            materials[] = {{"glass",5},{"copper_refined",3},{"diamond_cut",1}};
            text = "Magnified optic for high-tier rebel rifles.";
        };
        class rifle_flashlight {
            title = "Rifle Flashlight";
            category = "attachments";
            outputType = "gear";
            outputClass = "acc_flashlight";
            outputAmount = 1;
            requiredLevel = 30;
            craftTime = 36;
            cashCost = 350;
            craftingXP = 55;
            characterXP = 0;
            materials[] = {{"copper_refined",1},{"glass",1}};
            text = "Utility attachment for rebel rifles.";
        };
        class rebel_offroad {
            title = "Rebel Offroad";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "B_G_Offroad_01_F";
            outputAmount = 1;
            requiredLevel = 80;
            craftTime = 235;
            cashCost = 18500;
            craftingXP = 460;
            characterXP = 0;
            materials[] = {{"iron_refined",52},{"copper_refined",22},{"glass",10},{"oil_processed",10}};
            text = "Rebel garage vehicle delivered inactive to your garage.";
        };
        class rebel_lsv {
            title = "Qilin LSV";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "O_T_LSV_02_unarmed_F";
            outputAmount = 1;
            requiredLevel = 95;
            craftTime = 360;
            cashCost = 55000;
            craftingXP = 700;
            characterXP = 0;
            materials[] = {{"iron_refined",95},{"copper_refined",45},{"glass",18},{"oil_processed",18},{"diamond_cut",4}};
            text = "High-end rebel vehicle with a major resource requirement.";
        };
        class rebel_mrap {
            title = "Ifrit MRAP";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "O_MRAP_02_F";
            outputAmount = 1;
            requiredLevel = 100;
            craftTime = 620;
            cashCost = 140000;
            craftingXP = 1300;
            characterXP = 0;
            materials[] = {{"iron_refined",220},{"copper_refined",95},{"glass",34},{"oil_processed",46},{"diamond_cut",10}};
            text = "Armored rebel vehicle delivered inactive to your garage.";
        };
        class rebel_armed_offroad {
            title = "Armed Rebel Offroad";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "B_G_Offroad_01_armed_F";
            outputAmount = 1;
            requiredLevel = 100;
            craftTime = 680;
            cashCost = 185000;
            craftingXP = 1450;
            characterXP = 0;
            materials[] = {{"iron_refined",260},{"copper_refined",110},{"glass",36},{"oil_processed",50},{"diamond_cut",12}};
            text = "Heavy rebel vehicle build with the longest black-market requirements.";
        };
        class rebel_hummingbird {
            title = "Stripped Hummingbird";
            category = "vehicles";
            outputType = "vehicle";
            outputClass = "B_Heli_Light_01_stripped_F";
            outputAmount = 1;
            requiredLevel = 100;
            condition = "license_civ_pilot";
            craftTime = 760;
            cashCost = 210000;
            craftingXP = 1600;
            characterXP = 0;
            materials[] = {{"iron_refined",300},{"copper_refined",140},{"glass",55},{"oil_processed",72},{"diamond_cut",16}};
            text = "Rebel airframe delivered inactive to your garage.";
        };
    };
};
